add sun.misc.Unsafe
Auto-properties start: file:bundles/slf4j.log4j12_1.7.5.jar (org.osgi.framework.BundleException: Fragment bundles can not be started.)
log4j:WARN No appenders could be found for logger (org.eclipse.moquette.server.Server).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ERROR: Bundle org.eclipse.moquette.bundle [5] Error starting file:bundles/org.eclipse.moquette.bundle_0.7.0.SNAPSHOT.jar (org.osgi.framework.BundleException: Activator start error in bundle org.eclipse.moquette.bundle [5].)
java.lang.NoClassDefFoundError: sun/misc/Unsafe
        at com.lmax.disruptor.util.Util$1.run(Util.java:102)
        at com.lmax.disruptor.util.Util$1.run(Util.java:99)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.lmax.disruptor.util.Util.<clinit>(Util.java:108)
        at com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
        at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:70)
        at org.eclipse.moquette.spi.impl.SimpleMessaging.init(SimpleMessaging.java:88)
        at org.eclipse.moquette.server.Server.startServer(Server.java:90)
        at org.eclipse.moquette.server.Server.startServer(Server.java:76)
        at org.eclipse.moquette.server.Server.startServer(Server.java:59)
        at org.eclipse.moquette.bundle.Activator.start(Activator.java:37)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe not found by org.eclipse.moquette.bundle [5]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 17 more
ERROR: Bundle com.lmax.disruptor [6] Error starting file:bundles/com.lmax.disruptor_3.3.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle com.lmax.disruptor [6]: Unable to resolve 6.0: missing requirement [6.0] osgi.wiring.package; (osgi.wiring.package=sun.misc))
org.osgi.framework.BundleException: Unresolved constraint in bundle com.lmax.disruptor [6]: Unable to resolve 6.0: missing requirement [6.0] osgi.wiring.package; (osgi.wiring.package=sun.misc)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)

Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>