wrap HdrHistogram
Wrap non-bundle artifact HdrHistogram so the moquette bundle could be
resolved.

[WARNING] Skipping non-bundle artifact org.hdrhistogram:HdrHistogram:jar:2.1.4:compile

Auto-properties start: file:bundles/slf4j.log4j12_1.7.5.jar (org.osgi.framework.BundleException: Fragment bundles can not be started.)
ERROR: Bundle org.eclipse.moquette.bundle [4] Error starting file:bundles/org.eclipse.moquette.bundle_0.7.0.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.eclipse.moquette.bundle [4]: Unable to resolve 4.0: missing requirement [4.0] osgi.wiring.package; (osgi.wiring.package=org.HdrHistogram))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.eclipse.moquette.bundle [4]: Unable to resolve 4.0: missing requirement [4.0] osgi.wiring.package; (osgi.wiring.package=org.HdrHistogram)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Thread.java:745)

Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>